export const LOGIN_API = "LOGIN_API";

export const REGISTER_API = "REGISTER_API";

export const LOGOUT_API = "LOGOUT_API";

export const RESETPASSWORD_API = "RESETPASSWORD_API";

export const CONFIRMPASSWORD_API = "CONFIRMPASSWORD_API";

export const ATHELETE_RAGISTER_API = "ATHELETE_RAGISTER_API";
